### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Ben2701** [LeeviHalme/node-steam-openid#1]
I sry i hope its ok to wirte this here but i guessed you gues where the once that could help me the best. So i am trying to automate the login into a third party site with steam. Like for example csmoney. My biggest issue is that i dont know how or where i get the openidparam from. 

here you can see the request i mean. (That are all the reqeusts from Logging into the site)
![image](https://user-images.githubusercontent.com/73441563/103140205-493aa500-46e4-11eb-984a-afbdbda584f7.png)

And here are the parameters i mean that are sent with the login request
![image](https://user-images.githubusercontent.com/73441563/103140226-81da7e80-46e4-11eb-846d-0269fa534762.png)

I know this i probably quiet off topic but i still hope anyone can help me since i am realy tired of this shit i am alredy working on that for weeks. And if you need more context or anythink just say i just didnt wanted to spam picture here

**Comment by LeeviHalme** [comment]
Hi, this response most certainly will not help you anymore but I would need more details on what are you trying to get. The full response from Steam oAuth servers will be sent to the `returnUrl` you provide in the client instance. Could you get the params from that?

**Comment by LeeviHalme** [comment]
Closing this as a stale issue, feel free to open it again if the issue persists!
