### ISSUE TITLE
Publish 1.0.1 to NPM

### ISSUE THREAD

**Issue by Variiuz** [LeeviHalme/node-steam-openid#6]
Hello,
would be nice if you could bump the npm package up to the newest version (I made the pr) as it resolves some Axios vulnerabilities!
Thanks

**Comment by LeeviHalme** [comment]
> Hello,
> 
> would be nice if you could bump the npm package up to the newest version (I made the pr) as it resolves some Axios vulnerabilities!
> 
> Thanks

Fixed in PR #7 .
